FROM python:3.9-slim

WORKDIR /app

RUN pip install flask

COPY app_xss.py .

# Install tools for user exploration
RUN apt-get update && apt-get install -y curl iputils-ping && rm -rf /var/lib/apt/lists/*

CMD ["python", "app_xss.py"]
