/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description API information.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login with email and password.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current user information.
         */
        get: operations["get_current_user_info_api_auth_me_get"];
        /**
         * Update Current User
         * @description Update current user profile.
         */
        put: operations["update_current_user_api_auth_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh access token using refresh token cookie.
         */
        post: operations["refresh_token_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout user by clearing cookies.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scans
         * @description List user's scans with pagination.
         */
        get: operations["list_scans_api_scans__get"];
        put?: never;
        /**
         * Create Scan
         * @description Create a new security scan.
         *
         *     Scans are queued for asynchronous execution via the RQ worker queue.
         *     Falls back to FastAPI BackgroundTasks if Redis is unavailable.
         */
        post: operations["create_scan_api_scans__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan
         * @description Get a specific scan by ID.
         */
        get: operations["get_scan_api_scans__scan_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Scan
         * @description Delete a scan.
         */
        delete: operations["delete_scan_api_scans__scan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Scan
         * @description Start a pending scan.
         */
        post: operations["start_scan_api_scans__scan_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Scan
         * @description Cancel a running scan.
         */
        post: operations["cancel_scan_api_scans__scan_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vulnerabilities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Vulnerabilities
         * @description List vulnerabilities with filters.
         */
        get: operations["list_vulnerabilities_api_vulnerabilities__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vulnerabilities/scan/{scan_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vulnerability Summary
         * @description Get vulnerability count summary for a scan.
         */
        get: operations["get_vulnerability_summary_api_vulnerabilities_scan__scan_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vulnerabilities/{vuln_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vulnerability
         * @description Get a specific vulnerability by ID.
         */
        get: operations["get_vulnerability_api_vulnerabilities__vuln_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Vulnerability
         * @description Update vulnerability status (mark as false positive, verified, fixed).
         */
        patch: operations["update_vulnerability_api_vulnerabilities__vuln_id__patch"];
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat With Matrix
         * @description Send a message to the security expert chatbot.
         *     If scan_id is provided, findings from that scan are used as context.
         */
        post: operations["chat_with_matrix_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/xss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Xss Vulnerability
         * @description Vulnerable to Reflected XSS.
         *     Reflects the 'q' parameter directly without sanitization.
         */
        get: operations["xss_vulnerability_api_test_xss_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/sqli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sqli Vulnerability
         * @description Vulnerable to SQL Injection.
         *     Simulates a vulnerable SQL query.
         */
        get: operations["sqli_vulnerability_api_test_sqli_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/auth-bypass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Bypass
         * @description Vulnerable to Authentication Bypass/Weak Password.
         *     Accepts 'admin' / 'admin'.
         */
        post: operations["auth_bypass_api_test_auth_bypass_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Scan Id */
            scan_id?: number | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Response */
            response: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * ScanCreate
         * @description Schema for creating a new scan.
         */
        ScanCreate: {
            /**
             * Target Url
             * @description URL of the target to scan
             */
            target_url: string;
            /**
             * Target Name
             * @description Friendly name for the target
             */
            target_name?: string | null;
            /**
             * Scan Type
             * @description Type of scan: full, quick, or custom
             * @default full
             */
            scan_type: string;
            /**
             * Agents Enabled
             * @description List of agent types to enable
             * @default [
             *       "sql_injection",
             *       "xss",
             *       "auth",
             *       "api_security"
             *     ]
             */
            agents_enabled: string[];
            /**
             * Enable Waf Evasion
             * @description Enable advanced WAF evasion techniques. WARNING: This may trigger security alerts on target systems. Only use for authorized penetration testing with explicit permission.
             * @default false
             */
            enable_waf_evasion: boolean;
            /**
             * Waf Evasion Consent
             * @description User acknowledges the risks of WAF evasion testing
             * @default false
             */
            waf_evasion_consent: boolean;
        };
        /**
         * ScanListResponse
         * @description Schema for paginated scan list.
         */
        ScanListResponse: {
            /** Items */
            items: components["schemas"]["ScanResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /**
         * ScanResponse
         * @description Schema for scan response.
         */
        ScanResponse: {
            /** Id */
            id: number;
            /** Target Url */
            target_url: string;
            /** Target Name */
            target_name?: string | null;
            /** Scan Type */
            scan_type: string;
            status: components["schemas"]["ScanStatus"];
            /** Progress */
            progress: number;
            /**
             * Total Vulnerabilities
             * @default 0
             */
            total_vulnerabilities: number;
            /**
             * Critical Count
             * @default 0
             */
            critical_count: number;
            /**
             * High Count
             * @default 0
             */
            high_count: number;
            /**
             * Medium Count
             * @default 0
             */
            medium_count: number;
            /**
             * Low Count
             * @default 0
             */
            low_count: number;
            /**
             * Info Count
             * @default 0
             */
            info_count: number;
            /**
             * Technology Stack
             * @default []
             */
            technology_stack: string[];
            /**
             * Agents Enabled
             * @default []
             */
            agents_enabled: string[];
            /**
             * Enable Waf Evasion
             * @default false
             */
            enable_waf_evasion: boolean;
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * ScanStatus
         * @description Scan status enumeration.
         * @enum {string}
         */
        ScanStatus: "pending" | "queued" | "initializing" | "running" | "paused" | "completed" | "failed" | "cancelled" | "timed_out";
        /**
         * Severity
         * @description Vulnerability severity levels with numeric scores and color codes.
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        /**
         * Token
         * @description Schema for JWT token response.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /**
         * UserCreate
         * @description Schema for user registration.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
            /** Company */
            company?: string | null;
        };
        /**
         * UserLogin
         * @description Schema for user login.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description Schema for user response.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Username */
            username: string;
            /** Full Name */
            full_name?: string | null;
            /** Company */
            company?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Verified */
            is_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VulnerabilityListResponse
         * @description Schema for paginated vulnerability list.
         */
        VulnerabilityListResponse: {
            /** Items */
            items: components["schemas"]["VulnerabilityResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * VulnerabilityResponse
         * @description Schema for vulnerability response.
         */
        VulnerabilityResponse: {
            /** Id */
            id: number;
            vulnerability_type: components["schemas"]["VulnerabilityType"];
            severity: components["schemas"]["Severity"];
            /** Cvss Score */
            cvss_score?: number | null;
            /** Url */
            url: string;
            /** File Path */
            file_path?: string | null;
            /** Parameter */
            parameter?: string | null;
            /**
             * Method
             * @default GET
             */
            method: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Evidence */
            evidence?: string | null;
            /**
             * Ai Confidence
             * @default 0
             */
            ai_confidence: number;
            /** Ai Analysis */
            ai_analysis?: string | null;
            /** Remediation */
            remediation?: string | null;
            /** Remediation Code */
            remediation_code?: string | null;
            /**
             * Reference Links
             * @default []
             */
            reference_links: string[];
            /** Owasp Category */
            owasp_category?: string | null;
            /** Cwe Id */
            cwe_id?: string | null;
            /**
             * Is False Positive
             * @default false
             */
            is_false_positive: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /**
             * Is Fixed
             * @default false
             */
            is_fixed: boolean;
            /**
             * Is Suppressed
             * @default false
             */
            is_suppressed: boolean;
            /** Suppression Reason */
            suppression_reason?: string | null;
            /** Final Verdict */
            final_verdict?: string | null;
            /**
             * Action Required
             * @default true
             */
            action_required: boolean;
            /**
             * Detection Confidence
             * @default 0
             */
            detection_confidence: number;
            /**
             * Exploit Confidence
             * @default 0
             */
            exploit_confidence: number;
            /** Scope Impact */
            scope_impact?: {
                [key: string]: unknown;
            } | null;
            /** Detected By */
            detected_by?: string | null;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Scan Id */
            scan_id: number;
        };
        /**
         * VulnerabilitySummary
         * @description Summary of vulnerabilities by severity.
         */
        VulnerabilitySummary: {
            /** Total */
            total: number;
            /** Critical */
            critical: number;
            /** High */
            high: number;
            /** Medium */
            medium: number;
            /** Low */
            low: number;
            /** Info */
            info: number;
        };
        /**
         * VulnerabilityType
         * @description Comprehensive vulnerability types mapped to OWASP Top 10 2021 and CWE.
         * @enum {string}
         */
        VulnerabilityType: "sql_injection" | "nosql_injection" | "ldap_injection" | "command_injection" | "code_injection" | "xml_injection" | "xpath_injection" | "server_side_template_injection" | "xss_reflected" | "xss_stored" | "xss_dom" | "xss_mutation" | "weak_password" | "broken_authentication" | "session_fixation" | "insufficient_session_expiration" | "credential_stuffing" | "brute_force_vulnerable" | "sensitive_data_exposure" | "plaintext_transmission" | "weak_cryptography" | "hardcoded_credentials" | "pii_exposure" | "insecure_direct_object_reference" | "path_traversal" | "privilege_escalation" | "missing_authorization" | "cors_misconfiguration" | "security_misconfiguration" | "debug_mode_enabled" | "default_credentials" | "directory_listing" | "verbose_error_messages" | "missing_security_headers" | "outdated_component" | "vulnerable_dependency" | "server_side_request_forgery" | "open_redirect" | "csrf" | "clickjacking" | "xml_external_entity" | "insecure_deserialization" | "unrestricted_file_upload" | "file_inclusion" | "api_rate_limit_missing" | "api_authentication_bypass" | "mass_assignment" | "information_disclosure" | "source_code_disclosure" | "business_logic_flaw" | "race_condition" | "other";
        /**
         * VulnerabilityUpdate
         * @description Schema for updating vulnerability status.
         */
        VulnerabilityUpdate: {
            /** Is False Positive */
            is_false_positive?: boolean | null;
            /** Is Verified */
            is_verified?: boolean | null;
            /** Is Fixed */
            is_fixed?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_current_user_api_auth_me_put: {
        parameters: {
            query?: {
                full_name?: string;
                company?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_scans_api_scans__get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: components["schemas"]["ScanStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scan_api_scans__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scan_api_scans__scan_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan_api_scans__scan_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vulnerabilities_api_vulnerabilities__get: {
        parameters: {
            query?: {
                scan_id?: number | null;
                page?: number;
                size?: number;
                severity?: components["schemas"]["Severity"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vulnerability_summary_api_vulnerabilities_scan__scan_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilitySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vulnerability_api_vulnerabilities__vuln_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vuln_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vulnerability_api_vulnerabilities__vuln_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vuln_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VulnerabilityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_with_matrix_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    xss_vulnerability_api_test_xss_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sqli_vulnerability_api_test_sqli_get: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_bypass_api_test_auth_bypass_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
